server:
  port: 8080

providers:
  github:
    enabled: true
    path: /webhooks/github
    secret: ${GITHUB_WEBHOOK_SECRET}
    app_id: ${GITHUB_APP_ID}
    private_key_path: ${GITHUB_PRIVATE_KEY_PATH}
    base_url: https://api.github.com

watermill:
  driver: gochannel

rules:
  - when: action == "opened" && pull_request.draft == false
    emit: github.pr.opened.ready

  - when: action == "closed" && pull_request.merged == true
    emit: github.pr.merged

  - when: ref_type == "tag"
    emit: github.tag.created
