server:
  port: 8080

providers:
  bitbucket:
    enabled: true
    path: /webhooks/bitbucket
    secret: ${BITBUCKET_WEBHOOK_SECRET}
    token: ${BITBUCKET_ACCESS_TOKEN}
    base_url: https://api.bitbucket.org/2.0

watermill:
  driver: gochannel

rules:
  - when: pullrequest.state == "OPEN"
    emit: bitbucket.pr.opened

  - when: event_key == "repo:push"
    emit: bitbucket.repo.push
