server:
  port: 8080

providers:
  bitbucket:
    enabled: true
    secret: ${BITBUCKET_WEBHOOK_SECRET}
    base_url: https://api.bitbucket.org/2.0
    oauth_client_id: ${BITBUCKET_OAUTH_CLIENT_ID}
    oauth_client_secret: ${BITBUCKET_OAUTH_CLIENT_SECRET}

watermill:
  driver: gochannel

rules:
  - when: event_key == "pullrequest:created" && pullrequest.title == "WIP"
    emit: bitbucket.pr.draft

  - when: event_key == "pullrequest:created"
    emit: bitbucket.pr.created

  - when: event_key == "pullrequest:fulfilled"
    emit: bitbucket.pr.merged

  - when: event_key == "pullrequest:comment_created"
    emit: bitbucket.pr.comment.created

  - when: event_key == "issue:comment_created"
    emit: bitbucket.issue.comment.created

  - when: event_key == "repo:push" && push.changes[0].new.name == "main"
    emit: bitbucket.push.main

  - when: event_key == "repo:push"
    emit: bitbucket.repo.push
