server:
  port: 8080

providers:
  github:
    enabled: true
    secret: ${GITHUB_WEBHOOK_SECRET}
    app_id: ${GITHUB_APP_ID}
    private_key_path: ${GITHUB_PRIVATE_KEY_PATH}
    base_url: https://api.github.com

watermill:
  driver: amqp
  amqp:
    url: amqp://guest:guest@localhost:5672/
    mode: durable_queue

rules:
  - when: action == "opened" && pull_request.draft == false
    emit: pr.opened.ready

  - when: action == "opened" && pull_request.draft == true
    emit: github.pr.draft

  - when: action == "ready_for_review"
    emit: github.pr.ready

  - when: action == "synchronize"
    emit: github.pr.synchronized

  - when: action == "closed" && pull_request.merged == true
    emit: pr.merged

  - when: action == "created" && issue.pull_request.url != null
    emit: github.pr.comment.created

  - when: action == "created" && issue.pull_request.url == null
    emit: github.issue.comment.created

  - when: action == "submitted"
    emit: github.pr.review.submitted

  - when: action == "created" && pull_request.url != null
    emit: github.pr.review.comment.created

  - when: action == "created" && comment.commit_id != null
    emit: github.commit.comment.created

  - when: ref == "refs/heads/main"
    emit: github.push.main

  - when: ref_type == "tag"
    emit: release.tag.created
